Failed to compile.
src/app/products/[id]/page.tsx
Type error: Type 'ProductDetailsPageProps' does not satisfy the constraint 'PageProps'.
  Types of property 'params' are incompatible.
    Type '{ id: string; }' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]

Next.js build worker exited with code: 1 and signal: null
Error: Process completed with exit code 1.